# docker/Dockerfile.production

# Step 1
FROM node:20-alpine AS build
WORKDIR /app
COPY ../package*.json ./
RUN npm ci
COPY ../ ./
RUN npm run build

# Step 2
FROM nginx:1.27-alpine
COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf
WORKDIR /usr/share/nginx/html
COPY --from=build /app/dist/e-shop/browser ./

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
